org: srtamim
service: eduman-api

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-southeast-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    NODE_ENV: ${env:NODE_ENV, 'development'}

# Configure packaging to reduce size
package:
  individually: true
  patterns:
    - '!.git'
    - '!src/**'
    - '!test/**'
    - '!.serverless/**'
    - '!yarn.lock'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
